

export const INIT_SQUARE_MAP = 'INIT_SQUARE_MAP';

export const MOVE_BY_DIRECTIONS = 'MOVE_BY_DIRECTIONS';

export const CLEAR_NEW_POS = 'CLEAR_NEW_POS';


export const INCREASE_LEVEL = 'INCREASE_LEVEL';

export const RESET_LEVEL = 'RESET_LEVEL';
