
export const USER_LOGIN = 'USER_LOGIN';
export const FETCH_MY_MUSIC_LIST = 'FETCH_MY_MUSIC_LIST';
export const FETCH_RECOMMEND_MUSIC_LIST = 'FETCH_RECOMMEND_MUSIC_LIST';
export const SET_SINGLE_SELECTED_MUSIC_ID = 'SET_SINGLE_SELECTED_MUSIC_ID';
export const SET_MULTIPLE_SELECTED_MUSIC_IDS = 'SET_MULTIPLE_SELECTED_MUSIC_IDS';
